## Numpy

In [ ]:
#numpy fonction for array length

In [3]:
import numpy as np

In [10]:
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
vector_shape = vector.shape
matrix_shape = matrix.shape
print(vector_shape)
print(matrix_shape)

(3,)
(3, 3)


## Lire un Dataset avec Numpy

In [13]:
# Numpy fonction for reading dataset numpy.genfromtxt()

In [32]:
import numpy as np
world_alcohol = np.genfromtxt("world-alcohol.csv", delimiter = ",", dtype = "U75", skip_header = 1)
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [22]:
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)

float64


## Showing data Correctly

In [33]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [35]:
ivoire_1985 = world_alcohol[2, 4]
second_country = world_alcohol[1, 1]
print(ivoire_1985)
print(second_country)

1.62
Americas


In [46]:
countries = world_alcohol[:, 2]
alcohol_consumption = world_alcohol[0:2, 4]
print(countries)
print(alcohol_consumption)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']
['0' '0.5']


In [54]:
first_two_columns = world_alcohol[:, 0:2]
first_ten_years = world_alcohol[0:10, 0]
first_ten_rows = world_alcohol[0:10, :]
first_twenty_regions = world_alcohol[0:20, 1:3]
#print(first_two_columns)
#print(first_ten_years)
print(first_ten_rows, "\n")
print(first_twenty_regions)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']] 

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['

## Convert Data Type

In [6]:
#astype
Vector = np.array(['1', '2', '3'])
Vector = Vector.astype(float)

## Realize Mathematics Calculs with Numpy


In [7]:
#sum
#mean
#max

matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(matrix)
matrix.sum(axis = 1) ## axis 0 for Y and axis 1 for X

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([ 30,  75, 120])

## Calculation of Annual comsumption per habitat for a given country